# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76987549d110c8f826606275418c226e691177a36e53bc4f09daccfe71a694bac2ac751e7657467dc67719bc887386041f136bbfa97491784dbfb6203de1caf6

test:
  secret_key_base: 810dd3f8e747fcbbc86e9026585a80da4e36c27952d65b1601199c827c5fefaf9302e8310e62dd05b7dd82c54a79d55e7bc47261fcf3a1acaf1fee3bfd89b3f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
